### ISSUE TITLE
Link to "Play now" is dead

### ISSUE THREAD

**Issue by DrPepperBianco** [anirudhjoshi/fluid_table_tennis#3] opened 2021-08-08 13:09 UTC

**Comment by clort81** [comment] 2022-01-21 02:42
Yeah and i can't try it locally

**Comment by generic-user1** [comment] 2022-07-01 17:11
The link is currently `https://anirudhjoshi.github.com/fluid_table_tennis/`, but should be `https://anirudhjoshi.github.io/fluid_table_tennis/` instead. The `.com` should be replaced with a `.io`.

**Comment by generic-user1** [comment] 2022-07-01 17:42
Opened PR #4 to fix the issue. Project owner has been inactive for quite some time now though... seems unlikely that they will return to merge PR's anytime soon.

Manually working around the issue isn't too complicated though... just click the link as it is now, then change `.com` to `.io` in your browser's address bar and hit enter.

**Comment by anirudhjoshi** [comment] 2022-07-02 00:50
Merged thx

**Closed** 2022-07-02 00:50 UTC

**Comment by generic-user1** [comment] 2022-07-02 15:43
I stand corrected. Thanks 👍
